Bai 1

In [5]:
import torch
import torch.nn as nn

In [6]:
data = torch.Tensor([1, 2, 3]) #lam viec vs Torch phai chuyen sang kieu du lieu cua Torch la Tensor
data

tensor([1., 2., 3.])

In [7]:
softmax_function = nn.Softmax(dim=0)#1 list tuong ung voi mang 1 chieu, dim se the hien chieu, chieu o day = 0
output = softmax_function(data)#KQ: e^1/(e^1+e^2+e3)....
output

tensor([0.0900, 0.2447, 0.6652])

In [9]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x) / torch.sum(torch.exp(x), dim=0)
        total = x_exp.sum(0, keepdim=True)#0 la mang 1 chieu, keepdim=True tra ve KQ mang 1 chieu
        return x_exp / total

my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [10]:
class StableSoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        c =  torch.max(x, dim=0)#tinh max
        x_exp = torch.exp(x - c.values)
        total = x_exp.sum(0, keepdim=True)
        return x_exp / total

stable_softmax = StableSoftmax()
output = stable_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

Bai 2

In [69]:
from abc import ABC, abstractmethod
class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass

    def get_yob(self):
        return self._yob

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self._grade = grade

    def describe(self):
        print(f"Student - Name: {self._name} - Yob: {self._yob} - Grade {self._grade}")

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self._subject = subject

    def describe(self):
        print(f"Teacher - Name: {self._name} - Yob: {self._yob} - Subject {self._subject}")

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self._specialist = specialist

    def describe(self):
        print(f"Doctor - Name: {self._name} - Yob: {self._yob} - Specialist {self._specialist}")

In [70]:
student1 = Student('A', 2000, 10)
student1.describe()
teacher1 = Teacher('B', 1990, 'Math')
teacher1.describe()
doctor1 = Doctor('C', 1980, 'Neurology')
doctor1.describe()
tearcher2 = Teacher('D', 1995, 'Physics')
tearcher2.describe()

Student - Name: A - Yob: 2000 - Grade 10
Teacher - Name: B - Yob: 1990 - Subject Math
Doctor - Name: C - Yob: 1980 - Specialist Neurology
Teacher - Name: D - Yob: 1995 - Subject Physics


In [82]:
class Ward:
    def __init__(self, name):
        self.__name = name
        self.__list_people = []

    def add_person(self, person: Person):
        self.__list_people.append(person)

    def describe(self):
        print(f'Name: {self.__name}')
        for p in self.__list_people:
            p.describe()

    def count_doctors(self):
        counter = 0
        for p in self.__list_people:
            if isinstance(p, Doctor):
                counter += 1
        return counter

    def sort_yob(self):
        self.__list_people.sort(key=lambda x: x.get_yob(), reverse=True)#key: thong tin so sanh

    def compute_average(self):
        total = 0
        for p in self.__list_people:
            total += p.get_yob()
        return total / len(self.__list_people)

    def compute_average_teacher(self):
        counter = 0
        total = 0
        for p in self.__list_people:
            if isinstance(p, Teacher):
                counter += 1
                total += p.get_yob()
        return total / counter


In [84]:
ward1 = Ward('Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(doctor1)
ward1.add_person(tearcher2)

In [85]:
ward1.describe()

Name: Ward1
Student - Name: A - Yob: 2000 - Grade 10
Teacher - Name: B - Yob: 1990 - Subject Math
Doctor - Name: C - Yob: 1980 - Specialist Neurology
Teacher - Name: D - Yob: 1995 - Subject Physics


In [86]:
ward1.count_doctors()

1

In [87]:
ward1.sort_yob()

In [88]:
ward1.describe()

Name: Ward1
Student - Name: A - Yob: 2000 - Grade 10
Teacher - Name: D - Yob: 1995 - Subject Physics
Teacher - Name: B - Yob: 1990 - Subject Math
Doctor - Name: C - Yob: 1980 - Specialist Neurology


In [89]:
ward1.compute_average()

1991.25

In [90]:
ward1.compute_average_teacher()

1992.5

Bai 3

In [108]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_empty(self):
        return len(self.__stack) == 0

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, item):
        if self.is_full():
            raise Exception("Stack is full")
        self.__stack.append(item)

    def pop(self):
        if self.is_empty():
            raise Exception("Stack is empty")
        return self.__stack.pop()

    def top(self):
        if self.is_empty():
            return "Stack is empty"
        return self.__stack[-1]

In [109]:
my_stack = MyStack(3)
my_stack.is_empty()
my_stack.push(1)
my_stack.push(2)
my_stack.push(3)

In [111]:
my_stack.pop()

3

In [112]:
my_stack.top()

2

Bai 4

In [114]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_empty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, item):
        if self.is_full():
            raise Exception("Queue is full")
        self.__queue.append(item)

    def dequeue(self):
        if self.is_empty():
            raise Exception("Queue is empty")
        self.__queue.pop(0)

    def front(self):
        if self.is_empty():
            print("Queue is empty")
            return
        return self.__queue[0]

In [125]:
my_queue = MyQueue(3)
my_queue.is_empty()
my_queue.enqueue(4)
my_queue.enqueue(1)
my_queue.enqueue(2)

In [126]:
my_queue.is_full()

True

In [127]:
my_queue.dequeue()

In [128]:
my_queue.front()

1

In [129]:
import torch
import torch.nn as nn
data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round ( output [0]. item () , 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [149]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x) / torch.sum(torch.exp(x), dim=0)
        total = x_exp.sum(0, keepdim=True)#0 la mang 1 chieu, keepdim=True tra ve KQ mang 1 chieu
        return x_exp / total

data = torch . Tensor ([5 , 2 , 4])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [151]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x) / torch.sum(torch.exp(x), dim=0)
        total = x_exp.sum(0, keepdim=True)#0 la mang 1 chieu, keepdim=True tra ve KQ mang 1 chieu
        return x_exp / total

data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
#assert round ( output [0]. item () , 2) == 0.0
output

tensor([nan, nan, nan])

In [134]:

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        c =  torch.max(x, dim=0)#tinh max
        x_exp = torch.exp(x - c.values)
        total = x_exp.sum(0, keepdim=True)
        return x_exp / total

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [135]:
from abc import ABC, abstractmethod
class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass

    def get_yob(self):
        return self._yob

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self._grade = grade

    def describe(self):
        print(f"Student - Name: {self._name} - Yob: {self._yob} - Grade {self._grade}")

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self._subject = subject

    def describe(self):
        print(f"Teacher - Name: {self._name} - Yob: {self._yob} - Subject {self._subject}")

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self._specialist = specialist

    def describe(self):
        print(f"Doctor - Name: {self._name} - Yob: {self._yob} - Specialist {self._specialist}")

In [136]:
student1 = Student ( name =" studentZ2023 ", yob =2011 , grade ="6")
assert student1 . _yob == 2011
student1 . describe ()

Student - Name:  studentZ2023  - Yob: 2011 - Grade 6


In [137]:
teacher1 = Teacher ( name =" teacherZ2023 ", yob =1991 , subject =" History ")
assert teacher1 . _yob == 1991
teacher1 . describe ()

Teacher - Name:  teacherZ2023  - Yob: 1991 - Subject  History 


In [138]:
doctor1 = Doctor ( name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists ")
assert doctor1 . _yob == 1981
doctor1 . describe ()

Doctor - Name:  doctorZ2023  - Yob: 1981 - Specialist  Endocrinologists 


In [142]:
class Ward:
    def __init__(self, name):
        self.__name = name
        self.__list_people = []

    def add_person(self, person: Person):
        self.__list_people.append(person)

    def describe(self):
        print(f'Name: {self.__name}')
        for p in self.__list_people:
            p.describe()

    def count_doctors(self):
        counter = 0
        for p in self.__list_people:
            if isinstance(p, Doctor):
                counter += 1
        return counter

    def sort_yob(self):
        self.__list_people.sort(key=lambda x: x.get_yob(), reverse=True)#key: thong tin so sanh

    def compute_average(self):
        total = 0
        for p in self.__list_people:
            total += p.get_yob()
        return total / len(self.__list_people)

    def compute_average_teacher(self):
        counter = 0
        total = 0
        for p in self.__list_people:
            if isinstance(p, Teacher):
                counter += 1
                total += p.get_yob()
        return total / counter


In [147]:
student1 = Student ( name =" studentA ", yob =2010 , grade ="7")
teacher1 = Teacher ( name =" teacherA ", yob =1969 , subject =" Math ")
teacher2 = Teacher ( name =" teacherB ", yob =1995 , subject =" History ")
doctor1 = Doctor ( name =" doctorA ", yob =1945 , specialist =" Endocrinologists ")
#assert ward1 . count_doctors () == 1
doctor2 = Doctor ( name =" doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward ( name =" Ward1 ")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . count_doctors ()

2

In [152]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_empty(self):
        return len(self.__stack) == 0

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, item):
        if self.is_full():
            raise Exception("Stack is full")
        self.__stack.append(item)

    def pop(self):
        if self.is_empty():
            raise Exception("Stack is empty")
        return self.__stack.pop()

    def top(self):
        if self.is_empty():
            return "Stack is empty"
        return self.__stack[-1]

In [153]:
stack1 = MyStack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . is_full () )

False


In [154]:
stack1 = MyStack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . top () )

2


In [155]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_empty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, item):
        if self.is_full():
            raise Exception("Queue is full")
        self.__queue.append(item)

    def dequeue(self):
        if self.is_empty():
            raise Exception("Queue is empty")
        self.__queue.pop(0)

    def front(self):
        if self.is_empty():
            print("Queue is empty")
            return
        return self.__queue[0]

In [156]:
queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . is_full () )

False


In [157]:
print ( queue1 . front () )

1
